[project]
name = "enterprise-knowledge-forecaster"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "jupyterlab>=4.4.5",
    "langchain>=0.3.27",
    "matplotlib>=3.10.5",
    "networkx>=3.4.2",
    "numpy>=2.2.6",
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "plotly>=6.2.0",
    "python-docx>=1.2.0",
    "scikit-learn>=1.7.1",
    "streamlit>=1.48.0",
    "unstructured>=0.18.11",
]
